# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='public.proto',
  package='public',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpublic.proto\x12\x06public\"\x06\n\x04\x46\x61ke\"$\n\x04\x46\x61il\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"k\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12\x12\n\nserialized\x18\x03 \x01(\x0c\x12\x12\n\ntime_stamp\x18\x04 \x01(\x03\x12\x0f\n\x07timeout\x18\x05 \x01(\x07\"[\n\x08Response\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x04\x12&\n\x08sub_type\x18\x02 \x01(\x0e\x32\x14.public.ResponseType\x12\x12\n\nserialized\x18\x03 \x01(\x0c\">\n\x06Packet\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.public.PacketType\x12\x12\n\nserialized\x18\x02 \x01(\x0c*1\n\nPacketType\x12\x10\n\x0cTYPE_REQUEST\x10\x00\x12\x11\n\rTYPE_RESPONSE\x10\x01*/\n\x0cResponseType\x12\x10\n\x0cTYPE_SUCCESS\x10\x00\x12\r\n\tTYPE_FAIL\x10\x01\x62\x06proto3')
)

_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='public.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_RESPONSE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=336,
  serialized_end=385,
)
_sym_db.RegisterEnumDescriptor(_PACKETTYPE)

PacketType = enum_type_wrapper.EnumTypeWrapper(_PACKETTYPE)
_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='public.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_FAIL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=387,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_RESPONSETYPE)

ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
TYPE_REQUEST = 0
TYPE_RESPONSE = 1
TYPE_SUCCESS = 0
TYPE_FAIL = 1



_FAKE = _descriptor.Descriptor(
  name='Fake',
  full_name='public.Fake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=30,
)


_FAIL = _descriptor.Descriptor(
  name='Fail',
  full_name='public.Fail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='public.Fail.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='public.Fail.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=68,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='public.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='public.Request.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='public.Request.method_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized', full_name='public.Request.serialized', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='public.Request.time_stamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='public.Request.timeout', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=177,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='public.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='public.Response.response_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='public.Response.sub_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized', full_name='public.Response.serialized', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=270,
)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='public.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='public.Packet.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized', full_name='public.Packet.serialized', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=334,
)

_RESPONSE.fields_by_name['sub_type'].enum_type = _RESPONSETYPE
_PACKET.fields_by_name['type'].enum_type = _PACKETTYPE
DESCRIPTOR.message_types_by_name['Fake'] = _FAKE
DESCRIPTOR.message_types_by_name['Fail'] = _FAIL
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.enum_types_by_name['PacketType'] = _PACKETTYPE
DESCRIPTOR.enum_types_by_name['ResponseType'] = _RESPONSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fake = _reflection.GeneratedProtocolMessageType('Fake', (_message.Message,), dict(
  DESCRIPTOR = _FAKE,
  __module__ = 'public_pb2'
  # @@protoc_insertion_point(class_scope:public.Fake)
  ))
_sym_db.RegisterMessage(Fake)

Fail = _reflection.GeneratedProtocolMessageType('Fail', (_message.Message,), dict(
  DESCRIPTOR = _FAIL,
  __module__ = 'public_pb2'
  # @@protoc_insertion_point(class_scope:public.Fail)
  ))
_sym_db.RegisterMessage(Fail)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'public_pb2'
  # @@protoc_insertion_point(class_scope:public.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'public_pb2'
  # @@protoc_insertion_point(class_scope:public.Response)
  ))
_sym_db.RegisterMessage(Response)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'public_pb2'
  # @@protoc_insertion_point(class_scope:public.Packet)
  ))
_sym_db.RegisterMessage(Packet)


# @@protoc_insertion_point(module_scope)
